### ISSUE TITLE
HoustonLibrary

### ISSUE THREAD

**Issue by mdestafadilah** [NavpreetDevpuri/LyndaDownloader#2]
Your HoustonLibrary cookies not work anymore ... can you give everyone can edit cookies self?

**Comment by NavpreetDevpuri** [comment]
Yes, they block access for id.
But somehow our downloader's script is still working.

**Comment by mdestafadilah** [comment]
id is mean, Indonesia? i have one, but work for 3 month only, can you tell me, how to edit the cookies in your script?

**Comment by NavpreetDevpuri** [comment]
1) Open any video from any course in Google Chrome browser. 
2) Now press f12 to open developer's tools.
3) Open networking tab and clear all logs and refresh page. 
4) search for something like 'https://www.lynda.com/ajax/course/13673/156262/play' and you will see something like request headers and there will be a header named "cookies" copy those value.
5) put those value in script line number 56.

You can also create a link.
Open developer's tools and inspect element search for something like "course-id" and "video-id" get those values and put those values something like 'https://www.lynda.com/ajax/course/courseId/videoid/play'
After then moniter network logs and get cookies header value.

**Comment by NavpreetDevpuri** [comment]
You can create link if you find its difficult to find one. 
Open developer's tools and inspect element search for something like "course-id" and "video-id" get those values and put those value something like 'https://www.lynda.com/ajax/course/' + courseId + '/' + videoid + '/play'
After then moniter network logs and get cookies header value.

**Comment by mdestafadilah** [comment]
i will share my cookies here:
bcookie=7f4f365f6d254072945ead3f02f9571a8cc875ee8a8f429dbad5bb041f58f169; throttle-f9151a904e07fa0812b7b9fb20b6f1ab=1; throttle-66ae19c25d337eab52ef80bb97b39dd7=1; throttle-7566ffb605d4cb8c15225d8859a6efd3=1; throttle-b8b96eed8d81f42a88aadaadc5139c25=1; throttle-d3ebbd09ec7ecff8c4948ff79599614d=1; throttle-9620ede73ab0b3b8d0fe1e62763ad939=1; throttle-ad15fee1459e8f3e1ae3d8d711f77883=1; throttle-20fc2dfb0a81016faeebb960e94da216=1; _ga=GA1.2.1981352812.1575572649; throttle-2fa0e9b608dffa03090202330a823d2c=1; throttle-54c678a5add39d58a7d7411cae569603=1; show-member-tour-cta=true; throttle-7f0c15d211a720cccfeff5e84db0ec6e=1; throttle-2b03d60a3a4380742663b5f4066e4d2a=1; throttle-5348dd4a563290f2f066ced19befea6a=2; throttle-34d6c36979b1bc5f735cf8382b5963ae=1; throttle-81caf7c4bbc10c18b29b105cfcbcdbee=1; throttle-3c6decaab331b0e589231f32fc4b9a84=1; throttle-b8b1cb3ef236f57532c515db9614be44=1; player=%7B%22volume%22%3A0.8%2C%22muted%22%3Afalse%7D; throttle-85975e5888b0a2a3d27c273fd5637879=1; throttle-cb8048294d8a62ec98a5d38754e4a964=1; throttle-fcc41b5952df7ea0746eff3c71b72bc7=1; throttle-bf01e020137cb85eaa7a5e6a2f331834=1; throttle-a5ca6acbd2f547f2914c0b113231bee3=1; throttle-47481a8f590db61e7b4703e070ade640=1; signin-tooltip=2; throttle-cc6e24142c9b2f691b86349a86409bdb=1; tcookie=0b4e742d-98c0-48c2-843a-01f7e0307ca4; throttle-9ecc4e578ac856334c0a44bd43f10619=1; throttle-257d98eb91c98e6e0656104d4aa74214=1; litrk-srcveh=srcValue=or-search&vehValue=www.google.com&prevSrc=direct/none&prevVeh=direct/none; player_settings_1994613835_2=player_type=2&video_format=1&cc_status=2&window_extra_height=148&volume_percentage=50&resolution=540; throttle-5e100fc1cdc0162455722c3ef7edca5a=1; throttle-58c6d8583842e489e0411b9a1aad7aae=1; _gid=GA1.2.185947324.1580511157; SSOLogin=OrgUrl=https%3A%2F%2Flynda.com%2Fportal%2Fpatron%3Forg%3Dfreelibrary.org&OrgName=The%20Free%20Library%20of%20Philadelphia; player_settings_1995160571_2=player_type=2&video_format=1&cc_status=2&window_extra_height=148&volume_percentage=50&resolution=540; NSC_ed11_xxx-iuuqt_wt=ffffffff096d9e2c45525d5f4f58455e445a4a423661; plugin_list=; player_settings_0_2=player_type=2&video_format=1&cc_status=2&window_extra_height=148&volume_percentage=50&resolution=0; token=7d187b99-7d8f-4e3f-872f-5eeba5090dc3,3d0cadac0a4d3e44ced9e77729a63987,t/WD4lEGg/UUrIm8JxWU7yEKB5pJ5pRan5nPl84/VYaFFwdzZbdSWtp0PekhRQFomQt4oT0yBEWfyovshZ6VeU8ko/v1myKWFyfbyUars8qbBh+uJzah6pd/ameIVLb8QPbrGn89G9VZy7dQX7G2Rg==; LyndaAccess=LyndaAccess=2/1/2020 2:35:58 PM&p=0&data=9,9/1/2020,1,191505; LyndaLoginStatus=Member-Logged-In; ncp=1; _gat=1

----
when i run with python IDLE, give me some error, *invalid syntacts* , in line code like * end=' ', * any advice?

**Comment by NavpreetDevpuri** [comment]
Yes, first paste this long value in url field of Chrome so that it removes unwanted newlines after that copy value from url field. 
After that on line number 56 you can see 'cookie' : 'value' here value in written in single quotes ( ' ' )

**Comment by mdestafadilah** [comment]
I'm done doing thats, and the error is still exists .. when using your cookis too, it's same error too, this error haven ... 
![error-python](https://user-images.githubusercontent.com/5575882/73617284-8b33a600-464f-11ea-8c16-103393eb55ef.png)

do you test my cookies?

this my new cookies after your direction.

```html
bcookie=7f4f365f6d254072945ead3f02f9571a8cc875ee8a8f429dbad5bb041f58f169; throttle-f9151a904e07fa0812b7b9fb20b6f1ab=1; throttle-66ae19c25d337eab52ef80bb97b39dd7=1; throttle-7566ffb605d4cb8c15225d8859a6efd3=1; throttle-b8b96eed8d81f42a88aadaadc5139c25=1; throttle-d3ebbd09ec7ecff8c4948ff79599614d=1; throttle-9620ede73ab0b3b8d0fe1e62763ad939=1; throttle-ad15fee1459e8f3e1ae3d8d711f77883=1; throttle-20fc2dfb0a81016faeebb960e94da216=1; _ga=GA1.2.1981352812.1575572649; throttle-2fa0e9b608dffa03090202330a823d2c=1; throttle-54c678a5add39d58a7d7411cae569603=1; show-member-tour-cta=true; throttle-7f0c15d211a720cccfeff5e84db0ec6e=1; throttle-2b03d60a3a4380742663b5f4066e4d2a=1; throttle-5348dd4a563290f2f066ced19befea6a=2; throttle-34d6c36979b1bc5f735cf8382b5963ae=1; throttle-81caf7c4bbc10c18b29b105cfcbcdbee=1; throttle-3c6decaab331b0e589231f32fc4b9a84=1; throttle-b8b1cb3ef236f57532c515db9614be44=1; player=%7B%22volume%22%3A0.8%2C%22muted%22%3Afalse%7D; throttle-85975e5888b0a2a3d27c273fd5637879=1; throttle-cb8048294d8a62ec98a5d38754e4a964=1; throttle-fcc41b5952df7ea0746eff3c71b72bc7=1; throttle-bf01e020137cb85eaa7a5e6a2f331834=1; throttle-a5ca6acbd2f547f2914c0b113231bee3=1; throttle-47481a8f590db61e7b4703e070ade640=1; signin-tooltip=2; throttle-cc6e24142c9b2f691b86349a86409bdb=1; tcookie=0b4e742d-98c0-48c2-843a-01f7e0307ca4; throttle-9ecc4e578ac856334c0a44bd43f10619=1; throttle-257d98eb91c98e6e0656104d4aa74214=1; litrk-srcveh=srcValue=or-search&vehValue=www.google.com&prevSrc=direct/none&prevVeh=direct/none; player_settings_1994613835_2=player_type=2&video_format=1&cc_status=2&window_extra_height=148&volume_percentage=50&resolution=540; throttle-5e100fc1cdc0162455722c3ef7edca5a=1; throttle-58c6d8583842e489e0411b9a1aad7aae=1; _gid=GA1.2.185947324.1580511157; SSOLogin=OrgUrl=https%3A%2F%2Flynda.com%2Fportal%2Fpatron%3Forg%3Dfreelibrary.org&OrgName=The%20Free%20Library%20of%20Philadelphia; player_settings_1995160571_2=player_type=2&video_format=1&cc_status=2&window_extra_height=148&volume_percentage=50&resolution=540; NSC_ed11_xxx-iuuqt_wt=ffffffff096d9e2c45525d5f4f58455e445a4a423661; plugin_list=; player_settings_0_2=player_type=2&video_format=1&cc_status=2&window_extra_height=148&volume_percentage=50&resolution=0; token=7d187b99-7d8f-4e3f-872f-5eeba5090dc3,3d0cadac0a4d3e44ced9e77729a63987,t/WD4lEGg/UUrIm8JxWU7yEKB5pJ5pRan5nPl84/VYaFFwdzZbdSWtp0PekhRQFomQt4oT0yBEWfyovshZ6VeU8ko/v1myKWFyfbyUars8qbBh+uJzah6pd/ameIVLb8QPbrGn89G9VZy7dQX7G2Rg==; LyndaAccess=LyndaAccess=2/1/2020 2:35:58 PM&p=0&data=9,9/1/2020,1,191505; LyndaLoginStatus=Member-Logged-In; ncp=1; _gat=1
```

**Comment by NavpreetDevpuri** [comment]
You may be using python2.
Use python3.

**Comment by mdestafadilah** [comment]
no, i'm using python 3, i'm tested in python 2, it's not work too. i'm in windows.

i'm not expert in python, so i have no idea what wrong with thats line error code.

**Comment by NavpreetDevpuri** [comment]
Are you sure you are using Python 3.x? The syntax end=" " isn't available in Python 2.x because print is still a statement not function as it is in python 3.x.

**Comment by mdestafadilah** [comment]
Thanks Bro ... i have add `pyreadline` instead `readline` cz i'm on windows 10.

then add to your code:
```python
from pyreadline import Readline
readline = Readline()
```

then show me the error ..
![newErrorLyndadownloader](https://user-images.githubusercontent.com/5575882/73686229-2d0fcd00-46fa-11ea-8586-e713bd54c950.png)

but wait, i'm testing with idle interface, the same result ...
![lyndadownloader-idle-error](https://user-images.githubusercontent.com/5575882/73686418-824bde80-46fa-11ea-855b-5dde6bf45c08.png)

any advices? 

or you can refactoring your code, to add cookies, before connectiong to lynda.com ...

**Comment by NavpreetDevpuri** [comment]
check updates.
