### ISSUE TITLE
Add subtitles for Course.

### ISSUE THREAD

**Issue by HeinKoZin** [NavpreetDevpuri/LyndaDownloader#3]
**Please add subtitles downloader for courses.**

**Comment by NavpreetDevpuri** [comment]
I will try this.

**Comment by NavpreetDevpuri** [comment]
For now you can manually download subtitles as follow 

https://www.lynda.com/ajax/player/transcript?courseId=2244044&videoId=2259730

just replace courceId and videoId by appropriate values can found by inspecting videos list in dev tools.

after that save that file as .srt and open video in vlc media player or any other player that have a option to add subtitle file.

**Comment by NavpreetDevpuri** [comment]
resolved! check updates

**Comment by HeinKoZin** [comment]
Thanks bro.
