### ISSUE TITLE
Having an issue installing Pip

### ISSUE THREAD

**Issue by iamaguesthere** [NavpreetDevpuri/LyndaDownloader#5]
C:\Users\usernamehere >pip install requests
'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by NavpreetDevpuri** [comment]
'pip' is not recognized as an internal or external command,
operable program or batch 
> 'pip' is not recognized as an internal or external command,
> operable program or batch file.


Google that. 
Learn to Google, life will change.
