### ISSUE TITLE
It's still Active Devel?

### ISSUE THREAD

**Issue by mdestafadilah** [NavpreetDevpuri/LyndaDownloader#9]
Hi Dev, 

Do you still active maintenance, cz Lynda.com now is Linkedin.com all ready...

**Comment by NavpreetDevpuri** [comment]
Not maintaining it... But we can create a better script for linkedin... 

Will try to do that,  and i will need some linkedin learning account for that.

**Comment by mdestafadilah** [comment]
> Not maintaining it... But we can create a better script for linkedin...
> 
> Will try to do that, and i will need some linkedin learning account for that.

nice to hear that. cz now linked vidio tutorial have alot update recently... 

thanks for your fast response.

**Comment by NavpreetDevpuri** [comment]
@mdestafadilah just started new project [linkedin-learning-downloader](https://github.com/NavpreetDevpuri/linkedin-learning-downloader)
